"""Tests the part of dtypes that is accessible from Python."""
###################
###  WARNING!!! ###
###################
# This file has been autogenerated
from __future__ import print_function

import nose
from nose.tools import assert_equal, assert_not_equal, assert_raises, raises, \
    assert_almost_equal, assert_true, assert_false, assert_in

from numpy.testing import assert_array_equal, assert_array_almost_equal

import os
import numpy  as np

from rect import dtypes


# dtypeInt
def test_dtype_int():
    a = np.array([1, 42, -65, 18], dtype=dtypes.xd_int)
    #for x, y in zip(a, np.array([1, 42, -65, 18], dtype=dtypes.xd_int)):
    #    assert_equal(x, y)
    a[:] = [18, -65, 42, 1]
    #for x, y in zip(a, np.array([18, -65, 42, 1], dtype=dtypes.xd_int)):
    #    assert_equal(x, y)
    a = np.array([1, -65, 1, -65] + [42, 18, 42, 18], dtype=dtypes.xd_int)
    #for x, y in zip(a, np.array([1, -65, 1, -65] + [42, 18, 42, 18], dtype=dtypes.xd_int)):
    #    assert_equal(x, y)
    b =  np.array(([1, -65, 1, -65] + [42, 18, 42, 18])[::2], dtype=dtypes.xd_int)
    #for x, y in zip(a[::2], b):
    #    assert_equal(x, y)
    a[:2] = b[-2:]
    print(a)





if __name__ == '__main__':
    nose.run()
